# Generated by Django 5.0.6 on 2024-07-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('code', models.IntegerField(verbose_name='代码')),
                ('name', models.CharField(max_length=200, verbose_name='内容')),
                ('name_en', models.CharField(max_length=200, verbose_name='英语内容')),
                ('interval', models.IntegerField(verbose_name='调用间隔')),
                ('sensitivity', models.FloatField(verbose_name='灵敏度')),
                ('overlap_thresh', models.FloatField(verbose_name='阈值')),
                ('remark', models.TextField(verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('state', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '算法',
                'verbose_name_plural': '算法',
                'db_table': 'av_behavior',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('code', models.CharField(max_length=50, verbose_name='摄像头编号')),
                ('name', models.CharField(max_length=100, verbose_name='摄像头名称')),
                ('stream_name', models.CharField(max_length=200, verbose_name='视频流名称')),
                ('stream_state', models.BooleanField(verbose_name='视频流状态')),
                ('state', models.BooleanField(verbose_name='状态')),
                ('remark', models.CharField(max_length=200, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '摄像头',
                'verbose_name_plural': '摄像头',
                'db_table': 'av_camera',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('code', models.CharField(max_length=50, verbose_name='编号')),
                ('stream_app', models.CharField(max_length=50, verbose_name='视频流应用')),
                ('stream_name', models.CharField(max_length=100, verbose_name='视频流名称')),
                ('stream_video', models.CharField(max_length=100, verbose_name='视频流视频')),
                ('stream_audio', models.CharField(max_length=100, verbose_name='视频流音频')),
                ('behavior_code', models.CharField(max_length=50, verbose_name='算法行为编号')),
                ('interval', models.IntegerField(verbose_name='检测间隔')),
                ('sensitivity', models.IntegerField(verbose_name='灵敏度')),
                ('overlap_thresh', models.IntegerField(verbose_name='阈值')),
                ('remark', models.CharField(max_length=200, verbose_name='备注')),
                ('push_stream', models.BooleanField(verbose_name='是否推流')),
                ('push_stream_app', models.CharField(max_length=50, null=True, verbose_name='推流应用')),
                ('push_stream_name', models.CharField(max_length=100, null=True, verbose_name='推流名称')),
                ('state', models.IntegerField(default=0, verbose_name='布控状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '布控',
                'verbose_name_plural': '布控',
                'db_table': 'av_control',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='排序')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('state', models.IntegerField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'av_notification',
            },
        ),
    ]
