# Generated by Django 5.0.6 on 2024-07-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='behavior',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='behavior',
            name='last_update_time',
        ),
    ]
